/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistarRouteImport } from './routes/registar'
import { Route as LeitorRouteImport } from './routes/leitor'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as IndexRouteImport } from './routes/index'

const RegistarRoute = RegistarRouteImport.update({
  id: '/registar',
  path: '/registar',
  getParentRoute: () => rootRouteImport,
} as any)
const LeitorRoute = LeitorRouteImport.update({
  id: '/leitor',
  path: '/leitor',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/historico': typeof HistoricoRoute
  '/leitor': typeof LeitorRoute
  '/registar': typeof RegistarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/historico': typeof HistoricoRoute
  '/leitor': typeof LeitorRoute
  '/registar': typeof RegistarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/historico': typeof HistoricoRoute
  '/leitor': typeof LeitorRoute
  '/registar': typeof RegistarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analise' | '/historico' | '/leitor' | '/registar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analise' | '/historico' | '/leitor' | '/registar'
  id: '__root__' | '/' | '/analise' | '/historico' | '/leitor' | '/registar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseRoute: typeof AnaliseRoute
  HistoricoRoute: typeof HistoricoRoute
  LeitorRoute: typeof LeitorRoute
  RegistarRoute: typeof RegistarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registar': {
      id: '/registar'
      path: '/registar'
      fullPath: '/registar'
      preLoaderRoute: typeof RegistarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leitor': {
      id: '/leitor'
      path: '/leitor'
      fullPath: '/leitor'
      preLoaderRoute: typeof LeitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseRoute: AnaliseRoute,
  HistoricoRoute: HistoricoRoute,
  LeitorRoute: LeitorRoute,
  RegistarRoute: RegistarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
